// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class CouleurImpl_Stub
    extends java.rmi.server.RemoteStub
    implements Couleur, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_CMJ_0;
    private static java.lang.reflect.Method $method_RGB_1;
    
    static {
	try {
	    $method_CMJ_0 = Couleur.class.getMethod("CMJ", new java.lang.Class[] {});
	    $method_RGB_1 = Couleur.class.getMethod("RGB", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public CouleurImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of CMJ()
    public java.lang.String CMJ()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_CMJ_0, null, 8143808027482067273L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of RGB()
    public java.lang.String RGB()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_RGB_1, null, -1709171690974446798L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
